spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_prac?serverTimezone=UTC&useSSL=false
    username: root
    password: zsed1235
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture

  logging:
    level:
      org.hibernate.SQL: debug